---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr-config
  namespace: lidarr
spec:
  target:
    name: lidarr-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.xml: |-
          {{ .config }}
  data:
    - secretKey: config
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: lidarr-config
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: lidarr
spec:
  target:
    name: postgres
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: fd29533a-4227-476a-991c-b2becd1d54bd
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: fd29533a-4227-476a-991c-b2becd1d54bd
        metadataPolicy: None
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
